name: silent_hosting
description: A premium high-end hosting dashboard.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.5+1
  cupertino_icons: ^1.0.2
  lottie: ^3.1.2
  glassmorphism: ^3.0.0
  http: ^1.2.0
  speech_to_text: ^6.6.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true